project_id = "adventure-quest-platform"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/auth/callback"]
email_redirect_to = "http://localhost:5173/auth/verify"

[storage]
file_size_limit = "50MiB"
